### ISSUE TITLE
没必要用selenium

### ISSUE THREAD

**Issue by rty813** [xchangfeng/nwpu-yqtb#1]
没必要用selenium，直接用发送post请求模拟请求就可以了，还不用装chrome

**Comment by xchangfeng** [comment]
是的。
但要找出那些POST或GET请求的话，得一直抓了包看。Selenium的好处是快，一晚上就能弄好并测试完成打包。

**Comment by rty813** [comment]
其实还好，一共就一个Post请求，我是比较喜欢这种方式的，比较轻量。不过应付不了一些复杂的，动态加载js的页面。不过学校的这个做的还是很简陋的

**Comment by rty813** [comment]
往这个地址提交post请求就可以了：http://yqtb.nwpu.edu.cn/wx/ry/ry_util.jsp
同时要带一个header：`'Referer': 'http://yqtb.nwpu.edu.cn/wx/ry/jrsb.jsp'`

**Comment by dadaewqq** [comment]
定时任务不要搞在本地了吧，没服务器的话，推荐腾讯的云函数，免费额度完全够。
写个简单的post请求然后关键字判断提交成功与否发到server酱。
很稳定的。
